name: Issue report
description: Create a report to help us improve
labels: ["issue"]
body:
  - type: markdown
    attributes: dfdf
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: textarea
    id: what-happened
    attributes:
      label: dfdf
      description: A clear and concise description of what the issue is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce the behavior
      description: 
      placeholder: |
        1. Fetch a '...'
        2. Update the '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happen.
    validations:
      required: true      
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: JavaScript
    validations:
      required: false
  - type: input
    id: language-version
    attributes:
      label: Node version
      placeholder: Node v16.14.2
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Library version
      placeholder: razorpay-node v2.8.4
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other information about the problem here.
    validations:
      required: false
