# This workflow will build a Java project with Maven, run tests with JaCoCo, and analyze the code with SonarCloud
name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Jobs
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      
      - name: Debug Env variable
        run: |
          echo "Host is ${{ secrets.SONARQUBE_HOST }}"
