# This workflow will build a Java project with Maven, run tests with JaCoCo, and analyze the code with SonarCloud
name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Jobs
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      
      - name: Debug Env variable
        run: |
          echo "Host is ${{ secrets.SONARQUBE_HOST }}"
